# Welcome to Jekyll and Thank you for using Renge as your theme.

# Renge is designed by Junchao (www.junchaowang.com) and inspired by amination
# “のんのんびより” and named by one of the Characters "Renge Miyauchi (宮内 れんげ Miyauchi Renge)".
# If you have any questions, you can reach me via https://github.com/billyfish152 by submitting
# an issue or via email billyfish152@gmail.com.

# Please install jekyll-paginate before build it.
# sudo gem install jekyll-paginate in linux or MacOS.
# gem install jekyll-paginate in Windows.

# Renge supports categories and tags, which are defined in each of your posts.
# Also, You can add or removed links in /_includes/sider.html .
# please change the belowing settings to your own.

# Site settings
title: Renge
email: billyfish152@gmail.com
description: Renge is a Jekyll theme that is designed by Junchao (www.junchaowang.com) and inspired by amination “のんのんびより” and named by one of the Characters "Renge Miyauchi (宮内 れんげ Miyauchi Renge)".
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.junchaowang.com" # the base hostname & protocol for your site
twitter_username:
github_username:  billyfish152

# Build settings
markdown: kramdown
paginate: 3
gems: [jekyll-paginate]
paginate_path: "/page/:num"
